config/routes.rb
Rails.application.routes.draw do
  resources :shops
  root 'static_pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.page(params[:page]).per(100)
    # @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :zipcode, :address, :tel)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @raw_shops = Shop.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | JavaScript PlayGround
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    / script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"
  body
    = yield

app/views/shops/_form.html.slim
= form_for @shop do |f|
  - if @shop.errors.any?
    #error_explanation
      h2 = "#{pluralize(@shop.errors.count, "error")} prohibited this shop from being saved:"
      ul
        - @shop.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :zipcode
    = f.text_field :zipcode
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :tel
    = f.text_field :tel
  .actions = f.submit

app/views/shops/_shop.html.slim
.shop
  = "#{shop.name}: #{shop.zipcode}"

app/views/shops/edit.html.slim
h1 Editing shop

== render 'form'

=> link_to 'Show', @shop
'|
=< link_to 'Back', shops_path

app/views/shops/index.html.slim
h1 = link_to 'root', root_path
h1 Listing shops

#shops
  = render partial: 'shop', collection: @shops
.page-load-status
  .infinite-scroll-request
    | loading!!
    br
    = paginate @shops
  p.infinite-scroll-last
    | end of contents!!!
  p.infinite-scroll-error
    | this is error message

app/views/shops/new.html.slim
h1 New shop

== render 'form'

= link_to 'Back', shops_path

app/views/shops/show.html.slim
p#notice = notice

p
  strong Name:
  = @shop.name
p
  strong Zipcode:
  = @shop.zipcode
p
  strong Address:
  = @shop.address
p
  strong Tel:
  = @shop.tel

=> link_to 'Edit', edit_shop_path(@shop)
'|
=< link_to 'Back', shops_path

app/views/static_pages/index.html.slim
h1 StaticPages#index
p Find me in app/views/static_pages/index.html.slim

button#test_button test
text#sample this is sample text

br

= link_to 'shop_list', shops_path

br

- @raw_shops.each do |shop|
  = shop.name
  br